### ISSUE TITLE
Утечка памяти + хорошее README

### ISSUE THREAD

**Issue by abcdw** [myshov/xkbswitch-macosx#1]
Посмотри пожалуйста обсуждение https://github.com/lyokha/vim-xkbswitch/issues/17
- [x] Исправить утекший интерфейс
- [ ] Упоминуть в README про xcodebuild
- [ ] Избавиться от бинарников в проекте
- [x] Поставить ссылку на библитеку для плагина vim-xkbswitch в README этого репозитария

**Comment by myshov** [comment]
@abcdw @lyokha привет!
Интерфейс делал по-быстрому, забыл delete... Переделаю как предложил Алексей.
Что дополнительно указать в README?

**Comment by abcdw** [comment]
Было бы хорошо упомянуть как собирать и устанавливать https://developer.apple.com/library/ios/technotes/tn2339/_index.html
Мне кажется было бы удобнее, если бы либа лежала в этом же репозитории.
Было бы круто, если бы можно было ставить xkb-switch из brew.

**Comment by myshov** [comment]
@abcdw эти проекты создавались в Xcode. Я не использовал ни cmake, ни просто make для этого проекта. Все делал в Xcode. Я думаю если упоминать про сборку, то таким образом: "Скачайте Xcode из AppStore, откройте в нем файл проекта xkbswitch.xcodeproj" и т.д.

Библиотеку вынес отдельно, по сути, по той же причине, мне было удобнее тогда сделать два разных проекта. Ну и в README всегда есть ссылка на необходимые репозитарии.

Про brew интересная идея, спасибо, помониторю этот вопрос.

**Comment by myshov** [comment]
@abcdw да, еще поставлю ссылку на библитеку для плагина в README этого репозитария.

**Comment by abcdw** [comment]
@myshov То, что проекты создавались в xcode - это я понял : ) 
Мне кажется правильнее либо объеденить в один проект, либо хотя бы просто в один репозиторий.
Про сборку я предложил упомянуть про xcodebuild, как аналогию `cmake . && make` в оригинальном xkb-switch.
@lyokha как считаешь?

PS. Коммитить бинарники - как-то неправильно на мой взгляд.

**Comment by lyokha** [comment]
@abcdw Сорри, как-то пропустил упоминание и вопрос ко мне в этом треде. Лично я считаю, что реализации плагина для vim и бэкенды-переключатели раскладок не должны быть жестко связаны в единой сборке (и сейчас это так в случае Linux и Windows). Поэтому, принимая во внимание мою неопытность в программировании под MacOS, я не могу дать ответ о необходимости наличия бинарников в сборке бэкенда. Исходя из общей практики, наверное это нехорошо, но, покуда это мало влияет на дистрибуцию vim-xkbswitch, я соглашусь с любым вариантом.

**Comment by vbauerster** [comment]
Предлагаю положить бинарник в релиз. Вкладка "releases".

**Comment by myshov** [comment]
да, хорошая идея

Сделаю потом
