### ISSUE TITLE
Side question

### ISSUE THREAD

**Issue by sittim** [myshov/xkbswitch-macosx#10]
Alex, this question may not fit your application, but I am new to mac and cannot find an answer.  Any way to change the <left> key on mac into <ctrl> key?  Is there a text file in mac that I can edit that will change how the modifier keys will work?

**Comment by myshov** [comment]
Hi! I don't know which particular key you want to rebind but I think this answer on stackoverflow can help you https://stackoverflow.com/a/8437594/1675347

Also there is 3rd party utility for keyboard customization https://github.com/tekezo/Karabiner-Elements

**Comment by myshov** [comment]
I think this issue can be closed

**Comment by sittim** [comment]
Alex, yes, and thank you.  I settled with Karabiner.
